# .github/workflows/dev.yml

name: Stalone CLI B]

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  forces: 
    runs-on: ubuntu-latest
    container:
      image: fluidattacks/cli:latest
      
    steps: 
      - name: Run Stalone CLI
        run: skims scan ReDos/
